name: DeployOnPages
run-name: ${{ github.actor }} deployed site on GitHub Pages
on: 
  push:
    branches:
      - main
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install -upgrade pip
          pip install pyvis
      - name: Run build script
        run: python main.py
